[global]
        log file = /var/log/samba/log.%m
        security = user
        inherit acls = yes
        map acl inherit = yes
        acl group control = yes
        server multi channel support = yes
        bind interfaces only = yes
        #interfaces = "eno1;capability=RSS,capability=RDMA"
        interfaces = mac0

[NAS]
        path = /srv/smb/NAS
        read only = no
        writable = yes
        browsable = yes
        valid users = rawhide

[rawhide]
        path = /srv/smb/rawhide
        read only = no
        writable = yes
        browsable = yes
        valid users = rawhide

[Backup]
        path = /srv/smb/sakuya_backup
        read only = no
        writable = yes
        browsable = yes
        valid users = rawhide

[Scratch]
        path = /srv/smb/scratch
        read only = no
        writable = yes
        browsable = yes
        valid users = rawhide

[familyshare]
    path = /srv/smb/familyshare
    read only = no
    writable = yes
    browsable = yes
    valid users = familyshare