- name: "media to koakuma"
  type: "pull"
  connect:
    type: "http"
    server: "https://patchouli.gensoukyou.neet.works:13493"
    listener_name: "media_to_koakuma"
    client_identity: "koakuma.gensoukyou.neet.works"
  cron: "0 * * * *"
  root_fs: "koumakan/backups/patchouli/mediabackup"
  recv:
    execpipe:
    # mbuffer | unzstd | zfs receive
    - [ "/usr/local/bin/mbuffer", "-q", "-s", "1M", "-m", "1G" ]
    properties:
      override: {
        "canmount": "noauto",
        "special_small_blocks": 0
      }
    placeholder:
      encryption: off
  replication:
    concurrency:
      steps: 1
      size_estimates: 1
  pruning:
    concurrency: 1
    keep_sender:
      - type: regex
        negate: true
        regex: '^zrepl_'
      - type: grid
        grid: 1x24h(keep=all) | 72x1h | 14x1d | 4x7d | 1x30d
        regex: '^zrepl_'
    keep_receiver:
      - type: regex
        negate: true
        regex: '^zrepl_'
      - type: grid
        grid: 1x96h(keep=all) | 336x1h | 28x1d | 8x7d | 3x30d
        regex: '^zrepl_'
