- name: "mamizou zroot to koakuma"
  type: "pull"
  connect:
    type: "http"
    server: "https://mamizou.gensoukyou.neet.works:13493"
    listener_name: "mamizou zroot fanout"
    client_identity: "koakuma.gensoukyou.neet.works"
  cron: "25 * * * *"
  root_fs: "koumakan/backups/mamizou"
  recv:
    execpipe:
    - [ "unzstd" ]
    properties:
      override: {
        "canmount": "noauto"
      }
    placeholder:
      encryption: off
  replication:
    concurrency:
      steps: 1
      size_estimates: 8
  pruning:
    concurrency: 1
    keep_sender:
      - type: regex
        regex: '.*'
    keep_receiver:
      - type: regex
        negate: true
        regex: '^zrepl_'
      - type: grid
        grid: 1x48h(keep=all) | 168x1h | 14x1d | 4x1w
        regex: '^zrepl_'
