- name: "media to koakuma"
  type: source
  client_keys:
    - "koakuma.gensoukyou.neet.works"
  datasets:
    - pattern: "basement/library/NAS"
      recursive: true
    - pattern: "basement/library/familyshare"
      recursive: true
    - pattern: "basement/library/homes"
      recursive: true
    - pattern: "shelf/Media"
      recursive: true
  send:
    raw: false
    backup_properties: true
    compressed: true
    large_blocks: true
    embedded_data: true
  snapshotting:
    type: "periodic"
    prefix: "zrepl_"
    interval: "30m"
    written_threshold: 1024
    timestamp_format: "human"
  pruning:
    concurrency: 1

- name: "scratch to koakuma"
  type: source
  client_keys:
    - "koakuma.gensoukyou.neet.works"
  datasets:
    - pattern: "basement/library/scratch"
      recursive: true
  send:
    raw: false
    backup_properties: true
    compressed: true
    large_blocks: true
    embedded_data: true
  snapshotting:
    type: "periodic"
    prefix: "zrepl_"
    interval: "5m"
    written_threshold: 1024
    timestamp_format: "human"
  pruning:
    concurrency: 1

- name: "containers to koakuma"
  type: source
  client_keys:
    - "koakuma.gensoukyou.neet.works"
  datasets:
    - pattern: "basement/library/containers"
      recursive: true
    - pattern: "basement/library/containers/podman_volumes/hath"
      exclude: true
  send:
    raw: false
    backup_properties: true
    compressed: true
    large_blocks: true
    embedded_data: true
  snapshotting:
    type: "periodic"
    prefix: "zrepl_"
    interval: "5m"
    written_threshold: 1024
    timestamp_format: "human"
  pruning:
    concurrency: 1

