- name: "media to koakuma"
  type: source
  client_keys:
    - "koakuma.gensoukyou.neet.works"
  datasets:
    - pattern: "basement/library/NAS"
      recursive: true
    - pattern: "basement/library/familyshare"
      recursive: true
    - pattern: "basement/library/homes"
      recursive: true
  send:
    raw: false
    execpipe:
    # zfs send | zstd | mbuffer
    - [ "mbuffer", "-q", "-s", "1M", "-m", "1G" ]
    backup_properties: true
    compressed: true
    large_blocks: true
    embedded_data: true
  snapshotting:
    type: "periodic"
    prefix: "zrepl_"
    interval: "30m"
  pruning:
    concurrency: 1
